baseURL = "https://alejandro-sysadmin.github.io/portfolio/"
defaultContentLanguage = "es"
languageCode = "es-ES"
title = "Alejandro | Linux SysAdmin"
theme = "blowfish"
relativeURLs = true

[params]
  colorScheme = "blowfish"
  defaultAppearance = "dark"

