# --- CONFIGURACIÓN DE INFRAESTRUCTURA VISUAL ---
defaultAppearance = "dark"
disableThemeToggle = true

[homepage]
  layout = "profile"

[article]
  showReadingTime = false
  showWordCount = false
  showDate = false
  showAuthor = false
  showFeatureImage = true
  showFeatureImageWebp = true

[list]
  showCards = false
  showThumbnails = true
  groupByYear = false

[author]
  name = "Alejandro Peñafuerte Acosta"
  # NOTA: Usamos la ruta absoluta desde la raíz para el avatar
  image = "/portfolio/img/avatar.png"
  headline = "Administrador de Sistemas Linux"
  bio = "Automatización, infraestructura y resolución de problemas. Aquí documento configuraciones, despliegues y mi stack tecnológico diario."

  [[author.links]]
    linkedin = "https://www.linkedin.com/in/alejandro-pe%C3%B1afuerte-acosta-19a025235/"
  [[author.links]]
    github = "https://github.com/alejandro-sysadmin"
  [[author.links]]
    envelope = "mailto:alejandro2000.bormujos@gmail.com"
