# --- CONFIGURACIÓN MAESTRA DE INFRAESTRUCTURA ---
defaultAppearance = "dark"
disableThemeToggle = true

[header]
  layout = "basic"

[article]
  showReadingTime = false
  showWordCount = false
  showDate = false
  showAuthor = false
  showFeatureImage = true
  showFeatureImageWebp = true

[list]
  showCards = true
  showThumbnails = true
  groupByYear = false

[author]
  name = "Alejandro Peñafuerte Acosta"
  image = "img/avatar.png"
  headline = "Administrador de Sistemas Linux"
  bio = "Automatización, infraestructura y resolución de problemas. Documentando el stack tecnológico diario."

  [[author.links]]
    linkedin = "https://www.linkedin.com/in/alejandro-pe%C3%B1afuerte-acosta-19a025235/"
  [[author.links]]
    github = "https://github.com/alejandro-sysadmin"
  [[author.links]]
    envelope = "mailto:alejandro2000.bormujos@gmail.com"
